article:
    path:     /
    defaults: { _controller: "BionicUniversityWallBundle:Admin/Article:index" }

article_show:
    path:     /{id}/show
    defaults: { _controller: "BionicUniversityWallBundle:Admin/Article:show" }

article_new:
    path:     /new
    defaults: { _controller: "BionicUniversityWallBundle:Admin/Article:new" }

article_create:
    path:     /create
    defaults: { _controller: "BionicUniversityWallBundle:Admin/Article:create" }
    requirements: { _method: post }

article_edit:
    path:     /{id}/edit
    defaults: { _controller: "BionicUniversityWallBundle:Admin/Article:edit" }

article_update:
    path:     /{id}/update
    defaults: { _controller: "BionicUniversityWallBundle:Admin/Article:update" }
    requirements: { _method: post|put }

article_delete:
    path:     /{id}/delete
    defaults: { _controller: "BionicUniversityWallBundle:Admin/Article:delete" }
    requirements: { _method: post|delete }