news:
    path:     /
    defaults: { _controller: "BionicUniversityWallBundle:Admin/News:index" }

news_show:
    path:     /{id}/show
    defaults: { _controller: "BionicUniversityWallBundle:Admin/News:show" }

news_new:
    path:     /new
    defaults: { _controller: "BionicUniversityWallBundle:Admin/News:new" }

news_create:
    path:     /create
    defaults: { _controller: "BionicUniversityWallBundle:Admin/News:create" }
    requirements: { _method: news }

news_edit:
    path:     /{id}/edit
    defaults: { _controller: "BionicUniversityWallBundle:Admin/News:edit" }

news_update:
    path:     /{id}/update
    defaults: { _controller: "BionicUniversityWallBundle:Admin/News:update" }
    requirements: { _method: news|put }

news_delete:
    path:     /{id}/delete
    defaults: { _controller: "BionicUniversityWallBundle:Admin/News:delete" }
    requirements: { _method: news|delete }