admin_post:
    path:     /
    defaults: { _controller: "BionicUniversityWallBundle:Admin/Post:index" }

admin_post_show:
    path:     /{id}/show
    defaults: { _controller: "BionicUniversityWallBundle:Admin/Post:show" }

admin_post_new:
    path:     /new
    defaults: { _controller: "BionicUniversityWallBundle:Admin/Post:new" }

admin_post_create:
    path:     /create
    defaults: { _controller: "BionicUniversityWallBundle:Admin/Post:create" }
    requirements: { _method: post }

admin_post_edit:
    path:     /{id}/edit
    defaults: { _controller: "BionicUniversityWallBundle:Admin/Post:edit" }

admin_post_update:
    path:     /{id}/update
    defaults: { _controller: "BionicUniversityWallBundle:Admin/Post:update" }
    requirements: { _method: post|put }

admin_post_delete:
    path:     /{id}/delete
    defaults: { _controller: "BionicUniversityWallBundle:Admin/Post:delete" }
    requirements: { _method: post|delete }
