BionicUniversity\Bundle\WallBundle\Entity\Post:
    type: entity
    table: null
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        text:
            type: text
        createdAt:
            type: datetime
    manyToOne:
        author:
            targetEntity: BionicUniversity\Bundle\UserBundle\Entity\User
            inversedBy: post
        community:
            targetEntity: BionicUniversity\Bundle\CommunityBundle\Entity\Community
            inversedBy: posts
    lifecycleCallbacks: {  }
