BionicUniversity\Bundle\WallBundle\Entity\Wall:
    type: entity
    table: null
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    oneToMany:
        posts:
            targetEntity: BionicUniversity\Bundle\WallBundle\Entity\Post
            mappedBy: wall
    lifecycleCallbacks: {  }
