bionic_university_message:
    resource: "@BionicUniversityMessageBundle/Resources/config/routing.yml"

bionic_university_wall:
    resource: "@BionicUniversityWallBundle/Resources/config/routing.yml"

bionic_university_user:
    resource: "@BionicUniversityUserBundle/Resources/config/routing.yml"
    prefix:   /

bionic_university_community:
    resource: "@BionicUniversityCommunityBundle/Resources/config/routing.yml"
    prefix:   /

