bionic_university_messages:
    resource: "@BionicUniversityMessagesBundle/Resources/config/routing.yml"
    prefix:   /

bionic_university_group:
    resource: "@BionicUniversityGroupBundle/Resources/config/routing.yml"
    prefix:   /

