BionicUniversity\Bundle\CommunityBundle\Entity\Community:
    type: entity
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: '50'
        description:
            type: string
            length: 255
    oneToMany:
        memberships:
            targetEntity: BionicUniversity\Bundle\CommunityBundle\Entity\Community
            mappedBy: community
