BionicUniversity\Bundle\CommunityBundle\Entity\Community:
    type: entity
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: '50'
        description:
            type: string
            length: 255
        createdAt:
            type: date
    oneToOne:
        owner:
            targetEntity: BionicUniversity\Bundle\UserBundle\Entity\User
    oneToMany:
        memberships:
            targetEntity: BionicUniversity\Bundle\CommunityBundle\Entity\Membership
            mappedBy: community
            cascade: ['remove']
        posts:
            targetEntity: BionicUniversity\Bundle\WallBundle\Entity\Post
            mappedBy: community
