messages:
    path:     /messages
    defaults: { _controller: "BionicUniversityMessageBundle:Front/Message:messages",  }
messages_reply:
    path:     /messages/reply/{id}
    defaults: { _controller: "BionicUniversityMessageBundle:Front/Message:messages",  }
message_create_front:
    path:     /create
    defaults: { _controller: "BionicUniversityMessageBundle:Front/Message:create" }
    requirements: { _method: post }
message_conversation:
    path:   /messages/{id}
    defaults: { _controller: "BionicUniversityMessageBundle:Front/Message:messages" }
message_conversations:
    path:   /messages/
    defaults: { _controller: "BionicUniversityMessageBundle:Front/Message:messages" }

