create_post:
    path:     /create
    defaults: { _controller: "BionicUniversityWallBundle:Front/Post:create" }

delete_post:
    path:     /delete/{id}
    defaults: { _controller: "BionicUniversityWallBundle:Front/Post:delete" }