create_post:
    path:     /
    defaults: { _controller: "BionicUniversityWallBundle:Front/Post:create" }

delete_post:
    path:     /
    defaults: { _controller: "BionicUniversityWallBundle:Front/Post:delete" }