BionicUniversityWallBundle_post:
    resource: "@BionicUniversityWallBundle/Resources/config/routing/admin/post.yml"
    prefix:   /admin/post

BionicUniversityWallBundle_news:
    resource: "@BionicUniversityWallBundle/Resources/config/routing/admin/news.yml"
    prefix:   /admin/news