BionicUniversityWallBundle_admin_post:
    resource: "@BionicUniversityWallBundle/Resources/config/routing/admin/post.yml"
    prefix:   /admin/post

BionicUniversityWallBundle_article:
    resource: "@BionicUniversityWallBundle/Resources/config/routing/admin/article.yml"
    prefix:   /admin/article

BionicUniversityWallBundle_post:
    resource: "@BionicUniversityWallBundle/Resources/config/routing/front/post.yml"
    prefix:   /