community:
    path:     /
    defaults: { _controller: "BionicUniversityCommunityBundle:Community:index" }

community_show:
    path:     /{id}/show
    defaults: { _controller: "BionicUniversityCommunityBundle:Community:show" }

community_new:
    path:     /new
    defaults: { _controller: "BionicUniversityCommunityBundle:Community:new" }

community_create:
    path:     /create
    defaults: { _controller: "BionicUniversityCommunityBundle:Community:create" }
    requirements: { _method: post }

community_edit:
    path:     /{id}/edit
    defaults: { _controller: "BionicUniversityCommunityBundle:Community:edit" }

community_update:
    path:     /{id}/update
    defaults: { _controller: "BionicUniversityCommunityBundle:Community:update" }
    requirements: { _method: post|put }

community_delete:
    path:     /{id}/delete
    defaults: { _controller: "BionicUniversityCommunityBundle:Community:delete" }
    requirements: { _method: post|delete }
