BionicUniversity\Bundle\MessageBundle\Entity\Message:
    type: entity
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        author:
            type: string
            length: 255
        receiver:
            type: string
            length: 255
        body:
            type: text
    lifecycleCallbacks: {  }
