BionicUniversity\Bundle\UserBundle\Entity\Event:
    type: entity
    table: null
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: '50'
        name:
            type: text
        date:
            type: datetime
    manyToMany:
        users:
          targetEntity: BionicUniversity\Bundle\UserBundle\Entity\User
          inversedBy: events
