BionicUniversity\Bundle\UserBundle\Entity\Friendship:
    type: entity
    table: null
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        acceptanceStatus:
            type: integer
    manyToOne:
        userSender:
            targetEntity: BionicUniversity\Bundle\UserBundle\Entity\User
            inversedBy: requests
        userReceiver:
            targetEntity: BionicUniversity\Bundle\UserBundle\Entity\User
            inversedBy: invites

BionicUniversity\Bundle\UserBundle\Doctrine\ORM\FriendshipRepository:
    type: entity
    repositoryClass: BionicUniversity\Bundle\UserBundle\Doctrine\ORM\FriendshipRepository
