BionicUniversity\Bundle\UserBundle\Entity\Interest:
    type: entity
    table: null
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: '50'
        icon:
            type: string
            length: '50'
    manyToMany:
        users:
          targetEntity: BionicUniversity\Bundle\UserBundle\Entity\User
          mappedBy: interests
          cascade: ['persist']


