BionicUniversity\Bundle\UserBundle\Entity\Interest:
    type: entity
    table: null
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: '50'
        logo:
            type: string
            length: '255'
            nullable: true
    manyToMany:
        users:
          targetEntity: BionicUniversity\Bundle\UserBundle\Entity\User
          mappedBy: interests


