BionicUniversity\Bundle\UserBundle\Entity\User:
    type: entity
    table: null
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        firstName:
            type: string
            length: '50'
        lastName:
            type: string
            length: '50'
        position:
            type: string
            length: '100'
        sex:
            type: string
            length: '6'
        department:
            type: string
            length: '100'
        dateOfBirth:
            type: date
        gender:
            type: string
            length: '6'
    oneToMany:
        incomingMessages:
            targetEntity: BionicUniversity\Bundle\MessageBundle\Entity\Message
            mappedBy: toUser
        outcomingMessages:
            targetEntity: BionicUniversity\Bundle\MessageBundle\Entity\Message
            mappedBy: fromUser
        memberships:
            targetEntity: BionicUniversity\Bundle\UserBundle\Entity\User
            mappedBy: user
    lifecycleCallbacks: {  }
