bionic_university_user_homepage:
    path:     /hello/{name}
    defaults: { _controller: BionicUniversityUserBundle:Default:index }

BionicUniversityUserBundle_user:
        resource: "@BionicUniversityUserBundle/Resources/config/routing/user.yml"
        prefix:   /user
