BionicUniversityUserBundle_admin_user:
        resource: "@BionicUniversityUserBundle/Resources/config/routing/admin/user.yml"
        prefix:   /admin/user

BionicUniversityUserBundle_front_user:
        resource: "@BionicUniversityUserBundle/Resources/config/routing/front/user.yml"
        prefix:   /

BionicUniversityUserBundle_front_security:
        resource: "@BionicUniversityUserBundle/Resources/config/routing/front/security.yml"
        prefix:   /