BionicUniversity\Bundle\UserBundle\Entity\User.php:
    properties:
        firstName:
            - Type:
                type: string
                message: The value {{ value }} is not a valid {{ type }}.
            - Length:
                min: 2
                max: 50
                minMessage: "Your first name must be at least {{ limit }} characters length"
                maxMessage: "Your first name cannot be longer than {{ limit }} characters length"
        lastName:
            - Type:
                type: string
                message: The value {{ value }} is not a valid {{ type }}.
            - Length:
                min: 2
                max: 50
                minMessage: "Your last name must be at least {{ limit }} characters length"
                maxMessage: "Your last name cannot be longer than {{ limit }} characters length"
        position:
            - Type:
                type: string
                message: The value {{ value }} is not a valid {{ type }}.
            - Length:
                min: 2
                max: 100
                minMessage: "Your position name must be at least {{ limit }} characters length"
                maxMessage: "Your position name cannot be longer than {{ limit }} characters length"
        department:
            - Type:
                type: string
                message: The value {{ value }} is not a valid {{ type }}.
            - Length:
                min: 2
                max: 100
                minMessage: "Your department name must be at least {{ limit }} characters length"
                maxMessage: "Your department name cannot be longer than {{ limit }} characters length"
        dateOfBirth:
            - Date: ~
        gender:
            - Choice: { choices: [m, f], message: Choose a valid gender. }
        avatar:
            - Type:
                type: string
                message: The value {{ value }} is not a valid {{ type }}.
            - Length:
                min: 1
                max: 255