user_profile:
    path:     /id{id}
    defaults: { _controller: "BionicUniversityUserBundle:Front/User:profile" }

user_search:
    path:     /search
    defaults: { _controller: "BionicUniversityUserBundle:Front/User:search" }
