user_profile:
    path:     /id{id}
    defaults: { _controller: "BionicUniversityUserBundle:Front/User:profile" }
user_setting:
    path:     /settings{id}
    defaults: { _controller: "BionicUniversityUserBundle:Front/User:edit" }
user_update:
    path: /{id}/update
    defaults: { _controller: "BionicUniversityUserBundle:Front/User:update" }
    requirements: { _method: post|put }