user_profile:
    path:     /id{id}
    defaults: { _controller: "BionicUniversityUserBundle:Front/User:profile" }
user_setting:
    path:     /settings
    defaults: { _controller: "BionicUniversityUserBundle:Front/User:edit" }
user_update:
    path: /{id}/update
    defaults: { _controller: "BionicUniversityUserBundle:Front/User:update" }
    requirements: { _method: post|put }
fos_user_registration_confirmed:
    path:   /confirmed
    defaults: { _controller: "BionicUniversityUserBundle:Front/User:createPassword" }
friends:
    path: /friends
    defaults: { _controller: "BionicUniversityUserBundle:Front/User:friends" }
add_friend:
    path: /add/{id}
    defaults: { _controller:"BionicUniversityUserBundle:Front/User:add" }
remove_friend:
    path: /remove/{id}
    defaults: { _controller:"BionicUniversityUserBundle:Front/User:remove" }