user:
    path:     /
    defaults: { _controller: "BionicUniversityUserBundle:Admin/User:index" }

user_show:
    path:     /{id}/show
    defaults: { _controller: "BionicUniversityUserBundle:Admin/User:show" }

user_new:
    path:     /new
    defaults: { _controller: "BionicUniversityUserBundle:Admin/User:new" }

user_create:
    path:     /create
    defaults: { _controller: "BionicUniversityUserBundle:Admin/User:create" }
    requirements: { _method: post }

user_edit:
    path:     /{id}/edit
    defaults: { _controller: "BionicUniversityUserBundle:Admin/User:edit" }

user_update:
    path:     /{id}/update
    defaults: { _controller: "BionicUniversityUserBundle:Admin/User:update" }
    requirements: { _method: post|put }

user_delete:
    path:     /{id}/delete
    defaults: { _controller: "BionicUniversityUserBundle:Admin/User:delete" }
    requirements: { _method: post|delete }
admin_page:
    path: /admin
    defaults: { _controller: "BionicUniversityUserBundle:Admin/User:showAdminPage" }