message:
    path:     /
    defaults: { _controller: "BionicUniversityMessageBundle:message:index" }

message_show:
    path:     /{id}/show
    defaults: { _controller: "BionicUniversityMessageBundle:message:show" }

message_new:
    path:     /new
    defaults: { _controller: "BionicUniversityMessageBundle:message:new" }

message_create:
    path:     /create
    defaults: { _controller: "BionicUniversityMessageBundle:message:create" }
    requirements: { _method: post }

message_edit:
    path:     /{id}/edit
    defaults: { _controller: "BionicUniversityMessageBundle:message:edit" }

message_update:
    path:     /{id}/update
    defaults: { _controller: "BionicUniversityMessageBundle:message:update" }
    requirements: { _method: post|put }

message_delete:
    path:     /{id}/delete
    defaults: { _controller: "BionicUniversityMessageBundle:message:delete" }
    requirements: { _method: post|delete }
