bionic_university_community_homepage:
    path:     /hello/{name}
    defaults: { _controller: BionicUniversityCommunityBundle:Default:index }

BionicUniversityCommunityBundle_community:
        resource: "@BionicUniversityCommunityBundle/Resources/config/routing/community.yml"
        prefix:   /community
