parameters:
    bionic_university_community.event_listener.upload_listener.class: BionicUniversity\Bundle\CommunityBundle\EventListener\UploadListener
services:
    bionic_university_community.event_listener.upload_listener:
        class: %bionic_university_community.event_listener.upload_listener.class%
        arguments: [@doctrine.orm.entity_manager]
        tags:
        - { name: kernel.event_listener, event: oneup_uploader.post_persist, method: onUpload }

    bionic_university_community.admin.community:
        class: BionicUniversity\Bundle\CommunityBundle\Admin\CommunityAdmin
        arguments: [~, BionicUniversity\Bundle\CommunityBundle\Entity\Community, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: admin, label: Community}
