parameters:
#    bionic_university_community.example.class: BionicUniversity\Bundle\CommunityBundle\Example

services:
#    bionic_university_community.example:
#        class: %bionic_university_community.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
