parameters:
#    bionic_university_community.example.class: BionicUniversity\Bundle\CommunityBundle\Example

services:
#    bionic_university_community.example:
#        class: %bionic_university_community.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
    bionic_university_community.admin.community:
        class: BionicUniversity\Bundle\CommunityBundle\Admin\CommunityAdmin
        arguments: [~, BionicUniversity\Bundle\CommunityBundle\Entity\Community, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: admin, label: Community}
